spring:
  datasource:
    url: jdbc:mysql://39.105.19.41:3306/bootdo?Unicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: abc123
    #验证连接的有效性
    test-while-idle: true
    #获取连接时候验证，会影响性能
    test-on-borrow: false
    #在连接归还到连接池时是否测试该连接
    test-on-return: false
    validation-query: SELECT 1 FROM DUAL
    #空闲连接回收的时间间隔，与test-while-idle一起使用，设置5分钟
    time-between-eviction-runs-millis: 300000
    #连接池空闲连接的有效时间 ，设置30分钟
    min-evictable-idle-time-millis: 1800000
    initial-size: 50
    #最大连接数50
    max-active: 500
    #指定连接池等待连接返回的最大等待时间，毫秒单位
    max-wait: 30000
    #指定必须保持连接的最小值
    min-idle: 50
  #Redis配置
  redis:
    open: true  # 是否开启redis缓存  true开启   false关闭
    database: 0
    host: 39.105.19.41
    port: 6379
    password: # 密码（默认为空）
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0

# Mybatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hengan.aisearch.db.schema

log:
  path: /Users/wangxiaotao/Downloads/logs/aisearch/

swagger:
  show: true



